[package]
name = "disco-bird"
version = "1.0.0"
edition = "2021"
authors = ["HasChad", "Furriana Pawslot"]

[dependencies]
macroquad = {version = "0.4.8", features = ["audio"]}

[build-dependencies]
winres = "0.1.12"